name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Restore keystore
      - run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > smartautoclicker.jks.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch smartautoclicker.jks.asc > smartautoclicker/smartautoclicker.jks
    - name: Build with Gradle
      run: ./gradlew -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" bundle
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: smartautoclicker-debug
        path: smartautoclicker/build/outputs/bundle/release/smartautoclicker-release.aab

  tests:
    name: Run local unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Local unit tests with Gradle
      run: ./gradlew testDebugUnitTest
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

